### ISSUE TITLE
where is KEGGtranslator.jar?

### ISSUE THREAD

**Issue by 1austrartsua1** [cogsys-tuebingen/KEGGtranslator#11]
I think the title speaks for itself. There is no file called KEGGtranslator.jar so how am I supposed to run your code? Or am I supposed to compile this? If so, there are no installation/compilation guidelines. 

Where can I download KEGGtranslator.jar? By the way, it is not here: https://uni-tuebingen.de/fakultaeten/mathematisch-naturwissenschaftliche-fakultaet/fachbereiche/informatik/lehrstuehle/kognitive-systeme/software/

**Comment by draeger** [comment]
You are very close: KEGGtranslator is now hosted via GitHub, so you can find executables under [Releases](https://github.com/draeger-lab/KEGGtranslator/releases).

**Comment by draeger** [comment]
Thank you for this suggestion. A link is now also included in the README file, see 738a82956d824d4a945c70c4fd36de3d4fcc13d0.
